# https://github.com/neumanndaniel/kubernetes/blob/master/kind/single-node.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "192.168.0.103"
  apiServerPort: 6443
nodes:
  - role: control-plane
  - role: worker
  - role: worker
