---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: sub-my-logging-stack
spec:
  forProvider:
    manifest:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        namespace: operators
        name: my-logging-stack
      spec:
        channel: stable
        name: elastic-cloud-eck
        source: operatorhubio-catalog
        sourceNamespace: olm
  providerConfigRef:
    name: provider-config-dev
