apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oss-istio-default-1-11-5
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/j-mascarenhas-tc/gitops
    targetRevision: HEAD
    path: istio/overlay/1-11-5/oss-profiles/default/
  destination:
    server: https://192.168.0.103:6443
    namespace: istio-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
