apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oss-istio-demo-1-11-5
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/j-mascarenhas-tc/gitops
    targetRevision: HEAD
    path: istio/overlay/1-11-5/oss-profiles/demo/
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
