apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-lb-1-11-5
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/j-mascarenhas-tc/gitops
    targetRevision: HEAD
    path: istio/overlay/1-11-5/revision/ingressgateway/front-lb/
  destination:
    server: https://192.168.0.103:6443
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
