apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-ext-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "150"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/morningspace/capabilities-shim-gitops
    path: config/shared/crossplane-ext
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
