---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: olm
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/operator-framework/operator-lifecycle-manager
    path: deploy/upstream/quickstart
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
