apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: permissive-mtls
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/j-mascarenhas-tc/gitops
    targetRevision: HEAD
    path: istio/overlay/mtls/permissive/
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
