# Ensuring all namespace and cluster scoped resources are cleaned up
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-uninstall-job
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # hooks are defined here
    "helm.sh/hook": post-delete
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-post-uninstall-job
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: clean-resources
          image: quay.io/bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -x

              result=0

              # clean csv
              csvs=($(kubectl get csv -n operators -o name))
              if [[ -n ${csvs[@]} ]]; then
                kubectl delete ${csvs[@]} -n operators
                (( result+=$? ))
              fi

              exit "${result}"
      restartPolicy: Never
      serviceAccountName: argocd-application-controller
  backoffLimit: 1
