---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  namespace: operators
  name: {{.Values.metadata.name}}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  channel: stable
  name: elastic-cloud-eck
  source: operatorhubio-catalog
  sourceNamespace: olm
